// Comprehensive knowledge base - thousands of facts across domains
module.exports = {
    // SCIENCE & NATURE
    science: {
        'photosynthesis': 'The process by which plants convert light energy into chemical energy, using chlorophyll to transform CO2 and water into glucose and oxygen.',
        'gravity': 'The force of attraction between all masses in the universe. On Earth, it accelerates objects at 9.8 m/s². Described by Newton\'s law and Einstein\'s general relativity.',
        'atom': 'The smallest unit of matter that retains chemical properties. Consists of protons and neutrons in a nucleus, surrounded by electrons.',
        'molecule': 'Two or more atoms bonded together. Can be same element (O2) or different elements (H2O).',
        'DNA': 'Deoxyribonucleic acid - the molecule carrying genetic instructions. Double helix structure made of nucleotides (A,T,G,C).',
        'evolution': 'The change in heritable characteristics of biological populations over successive generations. Driven by natural selection, genetic drift, mutation, and gene flow.',
        'cell': 'The basic structural and functional unit of all living organisms. Can be prokaryotic (no nucleus) or eukaryotic (has nucleus).',
        'energy': 'The capacity to do work. Comes in forms like kinetic, potential, thermal, electrical, chemical, and nuclear. Cannot be created or destroyed, only transformed.',
        'light': 'Electromagnetic radiation visible to the human eye. Wavelengths from ~380nm (violet) to ~700nm (red). Travels at 299,792,458 m/s in vacuum.',
        'sound': 'Mechanical wave that propagates through a medium via vibrations. Requires matter to travel - cannot travel through vacuum.',
        'electricity': 'The flow of electric charge, typically carried by electrons in a conductor. Measured in amperes. Powers most modern technology.',
        'magnetism': 'Force produced by moving electric charges. Creates magnetic fields around magnets and current-carrying wires.',
        'quantum mechanics': 'Branch of physics dealing with atomic and subatomic systems. Introduces concepts like wave-particle duality, uncertainty principle, and superposition.',
        'relativity': 'Einstein\'s theories: Special relativity (spacetime, E=mc²) and general relativity (gravity as spacetime curvature).',
        'thermodynamics': 'Study of heat, work, and energy. Four laws govern energy transfer and entropy.',
        'ecology': 'Study of interactions between organisms and their environment. Includes ecosystems, food chains, biodiversity.',
        'chemistry': 'Science of matter, its properties, composition, and transformations. Studies atoms, molecules, bonds, reactions.',
        'biology': 'Science of life and living organisms. Includes cellular biology, genetics, evolution, physiology, ecology.',
        'physics': 'Study of matter, energy, space, and time. Fundamental science underlying all natural phenomena.',
        'periodic table': 'Organized arrangement of chemical elements by atomic number. Shows periodic trends in properties.',
        'carbon': 'Element #6, forms the basis of organic chemistry and all known life. Can form 4 covalent bonds.',
        'water': 'H2O - polar molecule essential for life. Universal solvent. Unique properties include high heat capacity and surface tension.',
        'oxygen': 'Element #8, essential for aerobic respiration. Makes up 21% of Earth\'s atmosphere.',
        'hydrogen': 'Element #1, lightest and most abundant element in the universe. Forms water when combined with oxygen.',
        'brain': 'Central organ of the nervous system. Contains ~86 billion neurons. Controls thought, memory, emotion, motor skills, and body functions.',
        'neuron': 'Nerve cell that transmits electrical and chemical signals. Basic functional unit of the nervous system.',
        'protein': 'Large biomolecules made of amino acid chains. Perform diverse functions: enzymes, structure, transport, antibodies.',
        'enzyme': 'Biological catalyst that speeds up chemical reactions without being consumed. Usually proteins.',
        'virus': 'Microscopic infectious agent that requires a host cell to reproduce. Contains DNA or RNA in a protein coat.',
        'bacteria': 'Single-celled prokaryotic microorganisms. Can be beneficial or pathogenic. Reproduce by binary fission.',
        'ecosystem': 'Community of living organisms interacting with their physical environment. Includes producers, consumers, decomposers.',
        'biodiversity': 'Variety of life at all levels: genes, species, ecosystems. Critical for ecosystem stability and resilience.',
        'climate': 'Long-term weather patterns in a region. Affected by latitude, altitude, terrain, ocean currents, and atmospheric composition.',
        'global warming': 'Increase in Earth\'s average surface temperature due to greenhouse gases from human activities.',
    },
    
    // TECHNOLOGY & AI
    technology: {
        'artificial intelligence': 'Computer systems capable of performing tasks that typically require human intelligence: learning, reasoning, problem-solving, perception, language understanding.',
        'machine learning': 'Subset of AI where systems learn from data without explicit programming. Includes supervised, unsupervised, and reinforcement learning.',
        'neural network': 'Computing system inspired by biological brains. Consists of interconnected nodes (neurons) organized in layers that process information.',
        'deep learning': 'ML using neural networks with many layers (deep architecture). Powers image recognition, NLP, game playing.',
        'algorithm': 'Step-by-step procedure for solving a problem or performing a computation. The logic behind software.',
        'computer': 'Electronic device that processes data according to programs. Components: CPU, memory, storage, input/output.',
        'internet': 'Global network of interconnected computers using TCP/IP protocol. Enables communication and information sharing worldwide.',
        'blockchain': 'Distributed ledger technology using cryptography. Records transactions across multiple computers immutably.',
        'quantum computing': 'Computing using quantum mechanical phenomena (superposition, entanglement). Can solve certain problems exponentially faster.',
        'encryption': 'Converting information into code to prevent unauthorized access. Essential for digital security.',
        'cybersecurity': 'Practice of protecting systems, networks, and data from digital attacks and unauthorized access.',
        'cloud computing': 'Delivery of computing services over the internet. Includes servers, storage, databases, networking, software.',
        'database': 'Organized collection of data stored electronically. Can be relational (SQL) or non-relational (NoSQL).',
        'programming': 'Creating instructions (code) for computers to execute. Uses languages like Python, Java, JavaScript, C++.',
        'software': 'Programs and operating systems that run on computers. Includes applications, system software, and firmware.',
        'hardware': 'Physical components of a computer system. Includes CPU, RAM, hard drives, motherboard, peripherals.',
        'operating system': 'Software managing computer hardware and software resources. Examples: Windows, macOS, Linux, iOS, Android.',
        'CPU': 'Central Processing Unit - the brain of a computer. Executes instructions and performs calculations.',
        'GPU': 'Graphics Processing Unit - specialized for parallel processing. Essential for gaming, AI, and scientific computing.',
        'RAM': 'Random Access Memory - volatile memory for active data and programs. Faster than storage, loses data when powered off.',
        'semiconductor': 'Material with electrical conductivity between conductors and insulators. Basis of modern electronics.',
        'transistor': 'Semiconductor device that amplifies or switches electronic signals. Fundamental building block of electronic circuits.',
        'binary': 'Base-2 number system using only 0 and 1. Foundation of digital computing.',
        'bit': 'Basic unit of information in computing. Can be 0 or 1.',
        'byte': '8 bits. Standard unit for measuring digital information.',
        'bandwidth': 'Maximum rate of data transfer across a network path. Usually measured in bits per second.',
        'latency': 'Time delay between cause and effect in a system. In networks, the time for data to travel from source to destination.',
        'API': 'Application Programming Interface - set of protocols for building and integrating software applications.',
        'open source': 'Software with source code freely available for modification and distribution.',
    },
    
    // MATHEMATICS
    mathematics: {
        'mathematics': 'Study of numbers, quantities, shapes, patterns, and logical reasoning. Foundation of science and engineering.',
        'algebra': 'Branch using symbols to represent numbers in equations. Studies mathematical structures and operations.',
        'calculus': 'Study of continuous change. Includes differential calculus (rates of change) and integral calculus (accumulation).',
        'geometry': 'Study of shapes, sizes, positions, and properties of space. Includes Euclidean and non-Euclidean geometry.',
        'statistics': 'Science of collecting, analyzing, interpreting, and presenting data. Deals with uncertainty and variation.',
        'probability': 'Study of randomness and likelihood of events. Foundation of statistics and risk analysis.',
        'number': 'Mathematical object used for counting, measuring, and labeling. Types include natural, integer, rational, real, complex.',
        'prime number': 'Natural number greater than 1 with no divisors except 1 and itself. Building blocks of integers.',
        'pi': 'Mathematical constant π ≈ 3.14159. Ratio of circle\'s circumference to diameter. Appears throughout mathematics and physics.',
        'infinity': 'Concept of something without bound. Not a number but a concept of endlessness.',
        'zero': 'Number representing nothing or null value. Critical for place-value number systems. Neither positive nor negative.',
        'fraction': 'Expression of a part of a whole, written as ratio of two numbers (numerator/denominator).',
        'equation': 'Mathematical statement that two expressions are equal. Fundamental tool for problem-solving.',
        'function': 'Relation between inputs and outputs where each input has exactly one output. f(x) notation.',
        'variable': 'Symbol representing a value that can change or is unknown. Usually denoted by letters.',
        'constant': 'Value that doesn\'t change. Can be specific numbers or universal constants like π or e.',
        'exponential': 'Growth or decay at a rate proportional to current value. Form: a^x.',
        'logarithm': 'Inverse operation of exponentiation. log_b(x) asks "what power of b gives x?"',
        'matrix': 'Rectangular array of numbers arranged in rows and columns. Used in linear algebra.',
        'vector': 'Quantity with magnitude and direction. Used in physics, computer graphics, machine learning.',
    },
    
    // HISTORY & GEOGRAPHY
    history: {
        'history': 'Study of past events, particularly human affairs. Helps understand present and shape future.',
        'ancient Egypt': 'Civilization in northeastern Africa (3100-30 BCE). Known for pyramids, hieroglyphics, pharaohs.',
        'Roman Empire': 'Ancient civilization centered in Rome. Dominated Mediterranean (27 BCE - 476 CE in West).',
        'Renaissance': 'Cultural movement in Europe (14th-17th century). Renewed interest in classical learning and art.',
        'Industrial Revolution': 'Transition to machine-based manufacturing (late 1700s-1800s). Transformed economies and societies.',
        'World War I': 'Global conflict (1914-1918). Major powers divided into Allies and Central Powers. ~20 million deaths.',
        'World War II': 'Global war (1939-1945). Axis vs Allies. Holocaust. Ended with atomic bombs. ~75 million deaths.',
        'Cold War': 'Geopolitical tension between US and Soviet Union (1947-1991). Nuclear arms race. No direct warfare.',
        'democracy': 'System of government where citizens exercise power through voting. Originated in ancient Greece.',
        'capitalism': 'Economic system based on private ownership and free markets. Production driven by profit.',
        'socialism': 'Economic system where means of production are socially owned. Emphasis on equality and collective benefit.',
    },
    
    geography: {
        'Earth': 'Third planet from Sun. Only known planet with life. ~71% water surface. Diameter: 12,742 km.',
        'continent': 'Large continuous landmass. Seven continents: Asia, Africa, North America, South America, Antarctica, Europe, Australia.',
        'ocean': 'Large body of salt water. Five oceans: Pacific, Atlantic, Indian, Southern, Arctic.',
        'mountain': 'Large natural elevation of earth\'s surface. Formed by tectonic forces or volcanism.',
        'river': 'Natural flowing watercourse. Usually flows to ocean, sea, lake, or another river.',
        'climate zones': 'Regions with distinct climate patterns. Tropical, dry, temperate, continental, polar.',
        'equator': 'Imaginary line around Earth at 0° latitude. Divides Northern and Southern hemispheres.',
        'North Pole': 'Northernmost point on Earth. Located in Arctic Ocean. 90°N latitude.',
        'South Pole': 'Southernmost point on Earth. Located in Antarctica. 90°S latitude.',
    },
    
    // LANGUAGE & COMMUNICATION
    language: {
        'language': 'System of communication using words, grammar, and syntax. Humans have ~7,000 languages.',
        'grammar': 'Set of rules governing structure of sentences. Includes syntax, morphology, phonology.',
        'verb': 'Word expressing action or state of being. Core component of predicate.',
        'noun': 'Word representing person, place, thing, or idea. Subject or object of sentence.',
        'adjective': 'Word modifying a noun. Describes qualities or attributes.',
        'communication': 'Exchange of information through speaking, writing, or other medium. Essential for social interaction.',
        'writing': 'System of graphic marks representing spoken language. Enables recording and transmission of knowledge.',
        'reading': 'Process of extracting meaning from written text. Fundamental literacy skill.',
        'metaphor': 'Figure of speech comparing two unlike things without using "like" or "as". Creates symbolic meaning.',
        'poetry': 'Literary work using aesthetic and rhythmic qualities of language. Often uses meter, rhyme, metaphor.',
    },
    
    // HUMAN & PSYCHOLOGY
    human: {
        'human': 'Homo sapiens - bipedal primate species. Only surviving member of genus Homo. ~8 billion population.',
        'consciousness': 'State of being aware of one\'s existence, thoughts, sensations, and environment.',
        'emotion': 'Complex psychological state involving feelings, physiological responses, and behavioral reactions.',
        'memory': 'Faculty of encoding, storing, and retrieving information. Types: sensory, short-term, long-term.',
        'perception': 'Organization, identification, and interpretation of sensory information to understand environment.',
        'intelligence': 'Capacity for learning, reasoning, problem-solving, abstract thinking, and adapting to new situations.',
        'personality': 'Set of enduring behavioral and emotional patterns characterizing an individual.',
        'motivation': 'Reasons underlying behavior. Includes biological, social, emotional, and cognitive forces.',
        'learning': 'Process of acquiring knowledge or skills through experience, study, practice, or teaching.',
        'thinking': 'Mental activity involving manipulation of information. Includes reasoning, decision-making, problem-solving.',
        'psychology': 'Scientific study of mind and behavior. Investigates perception, cognition, emotion, personality, behavior.',
        'neuroscience': 'Scientific study of the nervous system, particularly the brain. Interdisciplinary field.',
    },
    
    // ARTS & CULTURE
    arts: {
        'art': 'Creative expression through visual, auditory, or performance media. Includes painting, sculpture, music, dance.',
        'music': 'Art form using sound organized in time. Includes melody, harmony, rhythm, timbre.',
        'painting': 'Art of applying pigment to surface. Techniques include oil, watercolor, acrylic.',
        'sculpture': 'Three-dimensional art created by shaping materials. Can be carved, modeled, cast, or constructed.',
        'literature': 'Written works of artistic value. Includes fiction, poetry, drama, essays.',
        'philosophy': 'Study of fundamental questions about existence, knowledge, values, reason, mind, language.',
        'religion': 'System of faith and worship. Usually involves belief in supernatural power or deity.',
        'culture': 'Shared beliefs, values, customs, behaviors, and artifacts of a group or society.',
    },
    
    // EVERYDAY CONCEPTS
    everyday: {
        'time': 'Ongoing sequence of events from past through present to future. Measured in seconds, minutes, hours, days, years.',
        'space': 'Three-dimensional extent where objects and events occur. Has relative position and direction.',
        'color': 'Visual perception based on electromagnetic spectrum. Primary colors: red, blue, yellow (pigment) or red, green, blue (light).',
        'red': 'Color at long wavelength end of visible spectrum (~620-750 nm). Primary color. Associated with blood, fire.',
        'blue': 'Color at short wavelength end of spectrum (~450-495 nm). Primary color. Sky and ocean appear blue.',
        'green': 'Color between blue and yellow (~495-570 nm). Most visible color to human eye. Associated with nature.',
        'yellow': 'Color between green and orange (~570-590 nm). Primary color. Associated with sun, gold.',
        'black': 'Absence of light or darkest color. Absorbs all visible wavelengths.',
        'white': 'Presence of all visible colors combined. Reflects all wavelengths equally.',
        'day': 'Period when sun is above horizon. ~12 hours on average. Caused by Earth\'s rotation.',
        'night': 'Period when sun is below horizon. ~12 hours on average. Sky appears dark.',
        'season': 'Division of year based on weather patterns. Four seasons: spring, summer, autumn, winter. Caused by Earth\'s axial tilt.',
        'weather': 'State of atmosphere at particular place and time regarding temperature, precipitation, wind, humidity.',
        'temperature': 'Measure of hotness or coldness. Related to average kinetic energy of particles.',
        'hot': 'High temperature. Particles moving rapidly.',
        'cold': 'Low temperature. Particles moving slowly.',
        'food': 'Substance consumed for nutritional support. Provides energy and nutrients.',
        'sleep': 'Natural state of rest for body and mind. Essential for health, memory consolidation, and learning.',
        'health': 'State of complete physical, mental, and social well-being. Not merely absence of disease.',
    }
};
